import { spawnSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { E2E_CLIENT_BUILD_ENV } from "./env.js";

// Builds the browser bundle for the end-to-end run with the synthetic demo configuration and the
// Auth-emulator/deterministic-maps flags compiled in. The values are written to a gitignored
// .env.e2e file and the build runs with `--mode e2e`, because Vite gives mode-specific env files
// priority over a developer's .env.local — plain process-env injection loses that contest and
// would silently bake real local values into the test bundle. The output intentionally lands in
// dist/client — the exact directory the production server serves — so the tests exercise the
// real static pipeline. Run `npm run build` afterwards if you need a deployable bundle again.

export default function globalSetup(): void {
  const repositoryRoot = path.resolve(import.meta.dirname, "../../..");
  const indexHtml = path.join(repositoryRoot, "dist/client/index.html");

  if (process.env.PW_SKIP_BUILD === "1" && existsSync(indexHtml)) {
    console.log("PW_SKIP_BUILD=1 — reusing the existing dist/client bundle.");
    return;
  }

  const envFile = Object.entries(E2E_CLIENT_BUILD_ENV)
    .map(([key, value]) => `${key}=${value}`)
    .join("\n");
  writeFileSync(
    path.join(repositoryRoot, ".env.e2e"),
    `# Generated by tests/e2e/support/global-setup.ts on every end-to-end run; gitignored.\n# Synthetic demo values only — see tests/e2e/support/env.ts.\n${envFile}\n`,
  );

  const result = spawnSync("npx", ["vite", "build", "--mode", "e2e"], {
    cwd: repositoryRoot,
    stdio: "inherit",
    env: { ...process.env, NODE_ENV: "production" },
  });

  if (result.status !== 0) {
    throw new Error("The end-to-end client build failed.");
  }
  if (!existsSync(indexHtml)) {
    throw new Error("The end-to-end client build produced no dist/client/index.html.");
  }
}
